# Day 15

# Pandas Library 2nd Part

In [3]:
import pandas as pd

In [5]:
pip install pandas

Requirement already satisfied: pandas in c:\users\rohit\onedrive\pictures\bluestacks\lib\site-packages (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\rohit\onedrive\pictures\bluestacks\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\rohit\onedrive\pictures\bluestacks\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\rohit\onedrive\pictures\bluestacks\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\rohit\onedrive\pictures\bluestacks\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
df =pd.read_csv("https://media.githubusercontent.com/media/datablist/sample-csv-files/main/files/customers/customers-10000.csv")

In [7]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,2022-04-27,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,2022-01-17,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,2022-01-13,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,2020-04-14,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,2020-06-27,http://nixon.net/

In [8]:
df.columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')

In [10]:
df['City']

0       Lake Jeffborough
1             Aaronville
2            East Jordan
3       East Kristintown
4            Andresmouth
              ...
9995          Petersport
9996          Briggsport
9997      West Joyceport
9998      Camachochester
9999          Sparkstown
Name: City, Length: 10000, dtype: object

In [12]:
a = df['City'][0:10]

In [13]:
type(a)

pandas.core.series.Series

In [14]:
print(a)

0      Lake Jeffborough
1            Aaronville
2           East Jordan
3      East Kristintown
4           Andresmouth
5    Lake Madelineburgh
6            West Ralph
7            Ambershire
8           Barrettview
9            New Rickey
Name: City, dtype: object

In [19]:
l = ['swati','a2','a3','a4','a5','a6','a7','a8','a9','a10']

In [20]:
pd.Series(a, index = l)

swati    NaN
a2       NaN
a3       NaN
a4       NaN
a5       NaN
a6       NaN
a7       NaN
a8       NaN
a9       NaN
a10      NaN
Name: City, dtype: object

In [21]:
pd.Series(list(a), index = l)

swati      Lake Jeffborough
a2               Aaronville
a3              East Jordan
a4         East Kristintown
a5              Andresmouth
a6       Lake Madelineburgh
a7               West Ralph
a8               Ambershire
a9              Barrettview
a10              New Rickey
dtype: object

In [22]:
m1 = pd.Series([100,200,300,400,500],index = [1,2,3,4,5])

In [23]:
m1

1    100
2    200
3    300
4    400
5    500
dtype: int64

In [24]:
m2 = pd.Series([600,700,800,900,1000],index = [1,2,3,4,5])

In [25]:
m2

1     600
2     700
3     800
4     900
5    1000
dtype: int64

In [28]:
m3 = pd.concat([m1,m2])

In [29]:
m3

1     100
2     200
3     300
4     400
5     500
1     600
2     700
3     800
4     900
5    1000
dtype: int64

In [30]:
m3[1]

1    100
1    600
dtype: int64

In [31]:
m1*m2

1     60000
2    140000
3    240000
4    360000
5    500000
dtype: int64

In [33]:
m1+m2

1     700
2     900
3    1100
4    1300
5    1500
dtype: int64

In [34]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/

In [43]:
df.drop("Last Name", axis = 1, inplace = True)

In [44]:
df.head()

,Index,Customer Id,First Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/

In [45]:
df.head()

,Index,Customer Id,First Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/

In [48]:
df.drop(3, inplace = True)

In [49]:
df

,Index,Customer Id,First Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
4,5,5820deAdCF23EFe,Kathleen,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/
5,6,E1CDEaC63fDd5aA,Trevor,Maddox Group,Lake Madelineburgh,Senegal,+1-134-348-0265x9132,+1-313-882-4167,briangriffin@chang.org,2021-08-13,https://www.roberts.com/
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,DD0caa06ebf217c,Meghan,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,2022-04-27,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,2022-01-17,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,2022-01-13,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,2020-04-14,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,2020-06-27,http://nixon.net/

In [51]:
df.set_index("City",inplace = True)

In [52]:
df

,Index,Customer Id,First Name,Company,Country,Phone 1,Phone 2,Email,Subscription Date,Website
City,,,,,,,,,,
Lake Jeffborough,1,EB54EF1154C3A78,Heather,Mosley-David,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
Aaronville,2,10dAcafEBbA5FcA,Kristina,"Horn, Shepard and Watson",Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
East Jordan,3,67DAB15Ebe4BE4a,Briana,Irwin-Oneal,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
Andresmouth,5,5820deAdCF23EFe,Kathleen,Carson-Burch,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/
Lake Madelineburgh,6,E1CDEaC63fDd5aA,Trevor,Maddox Group,Senegal,+1-134-348-0265x9132,+1-313-882-4167,briangriffin@chang.org,2021-08-13,https://www.roberts.com/
...,...,...,...,...,...,...,...,...,...,...
Petersport,9996,DD0caa06ebf217c,Meghan,Richardson LLC,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,2022-04-27,http://thomas-ramos.com/
Briggsport,9997,C1C62ff90D0AfED,Jeremiah,Hodge-Nixon,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,2022-01-17,https://www.campbell.com/
West Joyceport,9998,2EfAa6Fe435A7DA,Peggy,Vang LLC,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,2022-01-13,http://www.george-scott.com/
Camachochester,9999,5dB06C3Fab5CCCb,Evan,Gould Ltd,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,2020-04-14,https://www.payne.info/
Sparkstown,10000,9903e8fF4D8Ff0F,Melissa,Burns-Holden,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,2020-06-27,http://nixon.net/

In [53]:
df.head()

,Index,Customer Id,First Name,Company,Country,Phone 1,Phone 2,Email,Subscription Date,Website
City,,,,,,,,,,
Lake Jeffborough,1,EB54EF1154C3A78,Heather,Mosley-David,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
Aaronville,2,10dAcafEBbA5FcA,Kristina,"Horn, Shepard and Watson",Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
East Jordan,3,67DAB15Ebe4BE4a,Briana,Irwin-Oneal,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
Andresmouth,5,5820deAdCF23EFe,Kathleen,Carson-Burch,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/
Lake Madelineburgh,6,E1CDEaC63fDd5aA,Trevor,Maddox Group,Senegal,+1-134-348-0265x9132,+1-313-882-4167,briangriffin@chang.org,2021-08-13,https://www.roberts.com/

In [54]:
df.reset_index()

,City,Index,Customer Id,First Name,Company,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,Lake Jeffborough,1,EB54EF1154C3A78,Heather,Mosley-David,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,Aaronville,2,10dAcafEBbA5FcA,Kristina,"Horn, Shepard and Watson",Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,East Jordan,3,67DAB15Ebe4BE4a,Briana,Irwin-Oneal,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,Andresmouth,5,5820deAdCF23EFe,Kathleen,Carson-Burch,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/
4,Lake Madelineburgh,6,E1CDEaC63fDd5aA,Trevor,Maddox Group,Senegal,+1-134-348-0265x9132,+1-313-882-4167,briangriffin@chang.org,2021-08-13,https://www.roberts.com/
...,...,...,...,...,...,...,...,...,...,...,...
9994,Petersport,9996,DD0caa06ebf217c,Meghan,Richardson LLC,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,2022-04-27,http://thomas-ramos.com/
9995,Briggsport,9997,C1C62ff90D0AfED,Jeremiah,Hodge-Nixon,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,2022-01-17,https://www.campbell.com/
9996,West Joyceport,9998,2EfAa6Fe435A7DA,Peggy,Vang LLC,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,2022-01-13,http://www.george-scott.com/
9997,Camachochester,9999,5dB06C3Fab5CCCb,Evan,Gould Ltd,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,2020-04-14,https://www.payne.info/
9998,Sparkstown,10000,9903e8fF4D8Ff0F,Melissa,Burns-Holden,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,2020-06-27,http://nixon.net/

# Making a data frame from a Dictionary

In [55]:
d = {"key":[1,2,3,4,5],
       "key2":[6,7,8,9,10],
       "key3":[11,12,13,14,15]
      }

In [56]:
print(d)

{'key': [1, 2, 3, 4, 5], 'key2': [6, 7, 8, 9, 10], 'key3': [11, 12, 13, 14, 15]}

In [57]:
pd.DataFrame(d)

   key  key2  key3
0    1     6    11
1    2     7    12
2    3     8    13
3    4     9    14
4    5    10    15

In [ ]:
df1 = pd.read_csv("")